<a href="https://colab.research.google.com/github/MariaMalchenko/KSVD/blob/main/Malchenko_hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
# 1. Одновимірний масив з першими 20-ма натуральними числами
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
# 1. Двовимірний масив 4x4, заповнений одиницями
mtrx_4x4 = np.ones((4, 4))
mtrx_4x4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
# 2. Масив 5x5 з випадковими дійсними числами в діапазоні від -1 до 1
mtrx_5x5 = np.random.uniform(-1, 1, (5, 5))
mtrx_5x5

array([[-0.86936703,  0.16803909, -0.22452836,  0.11062717,  0.73571507],
       [ 0.17814745, -0.46624659, -0.57142704,  0.4016452 ,  0.92174818],
       [-0.65772201,  0.78141426, -0.09320574,  0.3149353 ,  0.32657773],
       [ 0.83959454,  0.80932696, -0.16328425, -0.80632878, -0.0437021 ],
       [-0.05626191, -0.95248336,  0.15213852, -0.12633224, -0.2848927 ]])

In [11]:
# 3. Масив 3x3 з випадковими дійсними числами в діапазоні від 0 до 1
mtrx_3x3 = np.random.uniform(0, 1, (3, 3))
mtrx_3x3

array([[0.01752118, 0.81435625, 0.87735201],
       [0.37887407, 0.47643705, 0.93753492],
       [0.69184752, 0.32172262, 0.50188325]])

In [16]:
# 4. Два одновимірні масиви розміром 6 з випадковими цілими числами від 1 до 20.
# Поелементні операції додавання, віднімання, множення.
m1 = np.random.randint(1, 21, 6)
m2 = np.random.randint(1, 21, 6)
print(m1)
print(m2)
print("+ :", m1 + m2)
print("- :", m1 - m2)
print("* :", m1 * m2)

[16 20  7  6 11  3]
[ 2  9 12 16 13 12]
+ : [18 29 19 22 24 15]
- : [ 14  11  -5 -10  -2  -9]
* : [ 32 180  84  96 143  36]


In [18]:
# 5. Дві матриці 3x2 та 2x4, заповнені випадковими цілими числами, їх добуток
mtrx_3x2 = np.random.randint(1, 6, (3, 2))
mtrx_2x4 = np.random.randint(1, 6, (2, 4))
new_mtrx = np.dot(mtrx_3x2, mtrx_2x4)
print(mtrx_3x2)
print(mtrx_2x4)
print("Добуток матриць:\n", new_mtrx)


[[3 1]
 [3 5]
 [3 5]]
[[2 5 3 5]
 [1 3 4 3]]
Добуток матриць:
 [[ 7 18 13 18]
 [11 30 29 30]
 [11 30 29 30]]


In [25]:
# 6. Транспонування матриці 3x3
mtrx2_3x3 = np.random.uniform(0, 1, (3, 3))
print(mtrx2_3x3)
mtrx2_3x3.T

[[0.479836   0.56991782 0.54600506]
 [0.02703758 0.25964128 0.44288483]
 [0.15263308 0.55355871 0.26934425]]


array([[0.479836  , 0.02703758, 0.15263308],
       [0.56991782, 0.25964128, 0.55355871],
       [0.54600506, 0.44288483, 0.26934425]])

In [26]:
# 7. Дві матриці 3x3, їх різниця
A = np.random.randint(1, 11, (3, 3))
B = np.random.randint(1, 11, (3, 3))
subtraction = A - B
print(A)
print(B)
print("Різниця матриць:\n", subtraction)

[[10  9  1]
 [ 1  2  5]
 [ 6  8  7]]
[[ 3  3 10]
 [ 6  1  6]
 [ 9  4  2]]
Різниця матриць:
 [[ 7  6 -9]
 [-5  1 -1]
 [-3  4  5]]


In [28]:
# 8. Дві матриці 3x3, їх добуток
C = np.random.randint(-5, 6, (3, 3))
D = np.random.randint(-5, 6, (3, 3))
product_CD = np.dot(C, D)
print(C)
print(D)
print("Добуток матриць:\n", product_CD)

[[-1 -2  4]
 [-1 -4  5]
 [ 1  0 -3]]
[[-5 -3  0]
 [-2  2  4]
 [ 4 -1 -4]]
Добуток матриць:
 [[ 25  -5 -24]
 [ 33 -10 -36]
 [-17   0  12]]


In [29]:
# 9. Вектор-стовпчик, що містить суму елементів кожного рядка 3x3 матриці
E = np.random.uniform(-1, 1, (3, 3))
row_sums = np.sum(E, axis=1).reshape(-1, 1)
print(E)
print("Вектор-стовпчик сум рядків:\n", row_sums)

[[ 0.71796396  0.72894639  0.90309408]
 [-0.46994023 -0.56836572  0.56928412]
 [ 0.10253034 -0.45062171  0.45486627]]
Вектор-стовпчик сум рядків:
 [[ 2.35000443]
 [-0.46902183]
 [ 0.1067749 ]]
